const express = require('express');
const router = express.Router();
const { createEmployee, getEmployees, getEmployeeById, updateEmployee, deleteEmployee } = require('../controllers/employeeController');
const upload = require('../middleware/uploadMiddleware');
router.post('/', upload, createEmployee);
router.get('/', getEmployees);
router.get('/:id', getEmployeeById);
router.put('/:id', upload, updateEmployee);
router.delete('/:id', deleteEmployee);
module.exports = router;
